#!/usr/bin/with-contenv bash

DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-warning}

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

exec \
	s6-setuidgid abc /usr/bin/deluge-web \
	-d -c /config --loglevel=${DELUGE_LOGLEVEL}
