#!/usr/bin/with-contenv bash
# shellcheck shell=bash

DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-info}

if [[ -f /config/core.conf ]]; then
    DELUGED_PORT=$(grep '"daemon_port"' /config/core.conf | tr -cd "[:digit:]")
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 ${DELUGED_PORT:-58846}" \
        s6-setuidgid abc /usr/bin/deluged -c /config \
        -d --loglevel="${DELUGE_LOGLEVEL}"
