#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f /config/core.conf ]]; then
    cp /defaults/core.conf /config/core.conf
fi

mkdir -p /run/deluged-temp

# create torrents directory if it does not exist
if [[ ! -d /config/torrents ]]; then
    mkdir -p /config/torrents
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    # permissions
    lsiown -R abc:abc \
        /run/deluged-temp \
        /config

    # chown download directory if currently not set to abc
    if [[ -d /downloads ]]; then
        if [[ "$(stat -c '%U' /downloads)" != "abc" ]]; then
            lsiown -R abc:abc /downloads
        fi
    fi
fi
