#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f /config/core.conf ]]; then
    cp /defaults/core.conf /config/core.conf
fi

# permissions
lsiown -R abc:abc \
    /config

# chown download directory if currently not set to abc
if [[ -d /downloads ]]; then
    if [[ "$(stat -c '%U' /downloads)" != "abc" ]]; then
        lsiown -R abc:abc /downloads
    fi
fi

# create torrents directory if it does not exist
if [[ ! -d /config/torrents ]]; then
    mkdir -p /config/torrents
    lsiown abc:abc /config/torrents
fi
